name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          pkg-config \
          clang \
          llvm-dev \
          libclang-dev \
          libleptonica-dev \
          libtesseract-dev \
          tesseract-ocr \
          tesseract-ocr-rus \
          tesseract-ocr-eng \
          python3 \
          python3-pip

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: parser

    - name: Install maturin
      working-directory: parser
      run: pip3 install maturin

    - name: Run clippy
      working-directory: parser
      run: cargo clippy --release -- -D warnings

    - name: Build extension
      working-directory: parser
      run: maturin build --release

    - name: Run tests
      working-directory: parser
      run: cargo test --release
